In [30]:
#Script to pull transactions DECENTRALAND data from Opensea V1 Subgraph: https://thegraph.com/hosted-service/subgraph/messari/opensea-v1-ethereum

import requests
import json
import pandas as pd
from datetime import datetime

# Point to correct subgraph URL
url = 'https://api.thegraph.com/subgraphs/name/messari/opensea-v1-ethereum'

# initialize full_data
df1_fulldata = pd.DataFrame()
df2_fulldata = pd.DataFrame()
df_data = pd.DataFrame()

for i in range(0,6) :
    # Set query (which fetches Decentraland token records from Opensea subgraph ordered by timestamp in desc)
    query = '''query {
    trades(first: 1000, skip:%s, orderDirection: desc, orderBy: timestamp, where: {collection_contains: "0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d"}) {
        id
        tokenId
        priceETH
        timestamp
        collection{
          name
        }
        }
      }''' % (i*1000)


    # Make the request
    r = requests.post(url, json={'query': query})
    #print(r.status_code)
    #print(r.text)
    
    # JSON adjustment
    json_data = json.loads(r.text)
    
    # extract JSON to convert to a dataframe
    df_data = json_data['data']['trades']
    df1_fulldata = pd.DataFrame(df_data)
        
    df2_fulldata = pd.concat([df2_fulldata,df1_fulldata])
    

#Removing NULLS - Data Cleaning
dfV1 = df2_fulldata.dropna()

#Converting from Unix timestamp to datetime
dfV1['timestamp'] = pd.to_datetime(dfV1['timestamp'],unit='s')

# Create date field
dfV1['transaction_date'] = pd.to_datetime(dfV1['timestamp']).dt.date

#Removing extra data from columns : Cleaning
dfV1['collection'] = dfV1['collection'].map(lambda x: str(x)[10:-2])

print(dfV1)

                                                    id  \
0    0x91366bcdb476cdb66f99b9f8ff1e408e596d842bcdf3...
1    0x8103dcf1701e1806dfc45341fb2b5c577c81d9079043...
2    0x15724b6abd9065e8d79d4c638a0db8d030ca7120e8d1...
3    0xf16584bb807f3bd8cfb9271037cf166c39fbf0eb28dc...
4    0x3f2a093ecc73893cbd60e8b7e3c86a6823646e808089...
..                                                 ...
610  0xc505d53ff6353775a1d933676a11671be6cf8ec6a9bb...
611  0xe4a89aeb397da530558e4db7a09598e117581367c83d...
612  0xf1f90e1169c7b0945e11124e737dcd6958668cb254f9...
613  0xa6b0765ac5d3d5074dcfde4f6224be79adbef576b106...
614  0xbdec6eac54415407e151986b0273f8efd92e6c271263...

                                               tokenId priceETH  \
0    1157920892373161954235709850086879078110749711...      7.2
1             9868188640707215440437863615521278132314        6
2            11569600475311907757754736652680119189493        0
3    1157920892373161954235709850086879078154986419...      6.5
4            11909882842232846221218111260111887400865        0
..                                                 ...      ...
610          15993271245284107782778606549293105938582     1.75
611  1157920892373161954235709850086879078226445716...        1
612  1157920892373161954235709850086879078226445716...     0.95
613          18375247813730677027022228801315483418537     0.01
614          18375247813730677027022228801315483418537     0.01

              timestamp         collection transaction_date
0   2022-02-25 00:49:55  Decentraland LAND       2022-02-25
1   2022-02-24 05:54:29  Decentraland LAND       2022-02-24
2   2022-02-22 20:07:50  Decentraland LAND       2022-02-22
3   2022-02-22 04:27:27  Decentraland LAND       2022-02-22
4   2022-02-21 19:09:38  Decentraland LAND       2022-02-21
..                  ...                ...              ...
610 2018-07-21 21:57:24  Decentraland LAND       2018-07-21
611 2018-07-20 12:27:04  Decentraland LAND       2018-07-20
612 2018-07-20 10:32:46  Decentraland LAND       2018-07-20
613 2018-06-13 04:17:38  Decentraland LAND       2018-06-13
614 2018-06-13 04:01:38  Decentraland LAND       2018-06-13

[4615 rows x 6 columns]

In [31]:
#Script to pull transactions DECENTRALAND data from Opensea V2 Subgraph: https://thegraph.com/hosted-service/subgraph/messari/opensea-v2-ethereum

import requests
import json
import pandas as pd
from datetime import datetime

# Point to correct subgraph URL
url = 'https://api.thegraph.com/subgraphs/name/messari/opensea-v2-ethereum'

# initialize full_data
df1_fulldata = pd.DataFrame()
df2_fulldata = pd.DataFrame()
df_data = pd.DataFrame()

for i in range(0,4) :
    # Set query (which fetches Decentraland token records from Opensea subgraph ordered by timestamp in desc)
    query = '''query {
    trades(first: 1000, skip:%s, orderDirection: desc, orderBy: timestamp, where: {collection_contains: "0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d"}) {
        id
        tokenId
        priceETH
        timestamp
        collection{
          name
        }
        }
      }''' % (i*1000)


    # Make the request
    r = requests.post(url, json={'query': query})
    #print(r.status_code)
    #print(r.text)
    
    # JSON adjustment
    json_data = json.loads(r.text)
    
    # extract JSON to convert to a dataframe
    df_data = json_data['data']['trades']
    df1_fulldata = pd.DataFrame(df_data)
        
    df2_fulldata = pd.concat([df2_fulldata,df1_fulldata])
    

#Removing NULLS - Data Cleaning
dfV2 = df2_fulldata.dropna()

#Converting from Unix timestamp to datetime
dfV2['timestamp'] = pd.to_datetime(dfV2['timestamp'],unit='s')

# Create date field
dfV2['transaction_date'] = pd.to_datetime(dfV2['timestamp']).dt.date

#Removing extra data from columns : Cleaning
dfV2['collection'] = dfV2['collection'].map(lambda x: str(x)[10:-2])

print(dfV2)

                                                    id  \
0    0xf1faf1704a4781675686c1468cc11c31c71a0ce7b114...
1    0x9d1ffcf2a5962d2dab681a61a7206955f6ba3dafb2cf...
2    0xe6e075e28b2fd1fdfa5fbbdf04b0b0a3bb918bcc5dc8...
3    0x1f639adb12655cc898e1a415d30107012dada6c5572a...
4    0x27c90029377ecf8a21e68d01f6a3227481f88dfb0311...
..                                                 ...
980  0xdf2271a7c336898b3a63de5c5472975d36f4d777ec39...
981  0x8dbfc3d40c65408431048c1fbecf4d330675e677a1ed...
982  0x9a8a7f920e43748b0b8e6eb05c2ad73290c02473fc15...
983  0xaf9235f9897ab617cadc554b96df00203a83a351d51c...
984  0x3fbcbcbe46465c06a09d1d010f3f4804da9aff1ef6ac...

                                               tokenId            priceETH  \
0            25521177519070384759753095557382615859181                 3.5
1    1157920892373161954235709850086879078318321955...                 2.8
2             9868188640707215440437863615521278132233                 3.5
3    1157920892373161954235709850086879078488463138...  1.9250000000000003
4    1157920892373161954235709850086879078396586899...                   4
..                                                 ...                 ...
980  1157920892373161954235709850086879078515685728...                 4.5
981  1157920892373161954235709850086879078328530426...                 4.5
982          46278401901247631031018946610720476757997                 4.5
983  1157920892373161954235709850086879078321724779...               4.458
984  1157920892373161954235709850086879078522491375...                   5

              timestamp         collection transaction_date
0   2022-07-11 14:40:13  Decentraland LAND       2022-07-11
1   2022-06-27 16:44:32  Decentraland LAND       2022-06-27
2   2022-06-24 19:52:25  Decentraland LAND       2022-06-24
3   2022-06-23 02:18:47  Decentraland LAND       2022-06-23
4   2022-06-22 23:55:16  Decentraland LAND       2022-06-22
..                  ...                ...              ...
980 2022-02-19 23:09:23  Decentraland LAND       2022-02-19
981 2022-02-19 19:37:35  Decentraland LAND       2022-02-19
982 2022-02-19 17:08:17  Decentraland LAND       2022-02-19
983 2022-02-19 15:54:48  Decentraland LAND       2022-02-19
984 2022-02-19 07:44:36  Decentraland LAND       2022-02-19

[985 rows x 6 columns]

In [32]:
#Script to pull transactions DECENTRALAND data from Opensea Seaport Subgraph: https://thegraph.com/hosted-service/subgraph/messari/opensea-seaport-ethereum
import requests
import json
import pandas as pd
from datetime import datetime

# Point to correct subgraph URL
url = 'https://api.thegraph.com/subgraphs/name/messari/opensea-seaport-ethereum'

# initialize full_data
df1_fulldata = pd.DataFrame()
df2_fulldata = pd.DataFrame()
df_data = pd.DataFrame()

for i in range(0,4) :
    # Set query (which fetches Decentraland token records from Opensea subgraph ordered by timestamp in desc)
    query = '''query {
    trades(first: 1000, skip:%s, orderDirection: desc, orderBy: timestamp, where: {collection_contains: "0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d"}) {
        id
        tokenId
        priceETH
        timestamp
        collection{
          name
        }
        }
      }''' % (i*1000)


    # Make the request
    r = requests.post(url, json={'query': query})
    #print(r.status_code)
    #print(r.text)
    
    # JSON adjustment
    json_data = json.loads(r.text)
    
    # extract JSON to convert to a dataframe
    df_data = json_data['data']['trades']
    df1_fulldata = pd.DataFrame(df_data)
        
    df2_fulldata = pd.concat([df2_fulldata,df1_fulldata])
    

#Removing NULLS - Data Cleaning
dfSeaport = df2_fulldata.dropna()

#Converting from Unix timestamp to datetime
dfSeaport['timestamp'] = pd.to_datetime(dfSeaport['timestamp'],unit='s')

# Create date field
dfSeaport['transaction_date'] = pd.to_datetime(dfSeaport['timestamp']).dt.date

#Removing extra data from columns : Cleaning
dfSeaport['collection'] = dfSeaport['collection'].map(lambda x: str(x)[10:-2])

print(dfSeaport)

                                                    id  \
0    0x4cec98fe6bb429b5f93f5f0b800001a2de0e276ca503...
1    0x1c3d526ac2599057e759268d58307881667218a4649a...
2    0xc4381bc367695c9629763311ba0580869166c7f4da7c...
3    0x0e89f66a3c9787430e693084dafabc5802d42b70e748...
4    0x47b2f2f3fcc2af5c3da9117547acb1036e7befe79f19...
..                                                 ...
303  0x393d6f4be10429d17e18dbb88381408e1fe8daaf4b42...
304  0xbe27f6f4713ecda703dc5dbc4b9fa4b3031afebb3e53...
305  0x857a4bf0d8f0a8433752bb3f6d9406a799e272d82732...
306  0x05d3a9d3b294a1cb0d29925f21d8429ec36b4667a3f3...
307  0x4a8a09844ee4e0ee5f0097b825f3dddc39d1654f350e...

                                               tokenId priceETH  \
0            26882306986754138613606593987109688705054      2.3
1    1157920892373161954235709850086879078029081943...    1.787
2            11229318108390969294291362045248350978064      1.9
3    1157920892373161954235709850086879078029081943...     1.78
4            26542024619833200150143219379677920493464    1.788
..                                                 ...      ...
303  1157920892373161954235709850086879078362558663...    3.397
304  1157920892373161954235709850086879078372767134...     3.75
305  1157920892373161954235709850086879078372767134...     3.75
306  1157920892373161954235709850086879078369364310...     3.75
307  1157920892373161954235709850086879078090332769...      3.3

              timestamp         collection transaction_date
0   2022-09-22 15:05:23  Decentraland LAND       2022-09-22
1   2022-09-21 23:23:47  Decentraland LAND       2022-09-21
2   2022-09-21 22:46:59  Decentraland LAND       2022-09-21
3   2022-09-21 20:11:47  Decentraland LAND       2022-09-21
4   2022-09-21 11:36:59  Decentraland LAND       2022-09-21
..                  ...                ...              ...
303 2022-06-15 16:38:39  Decentraland LAND       2022-06-15
304 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
305 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
306 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
307 2022-06-14 19:33:20  Decentraland LAND       2022-06-14

[308 rows x 6 columns]

In [33]:
#Merging the above 3 dataframes into one
frames = [dfV1, dfV2, dfSeaport]

df = pd.concat(frames)
df.reset_index(inplace=True)
df = df.drop(['index'], axis=1)

print(df)

                                                     id  \
0     0x91366bcdb476cdb66f99b9f8ff1e408e596d842bcdf3...
1     0x8103dcf1701e1806dfc45341fb2b5c577c81d9079043...
2     0x15724b6abd9065e8d79d4c638a0db8d030ca7120e8d1...
3     0xf16584bb807f3bd8cfb9271037cf166c39fbf0eb28dc...
4     0x3f2a093ecc73893cbd60e8b7e3c86a6823646e808089...
...                                                 ...
5903  0x393d6f4be10429d17e18dbb88381408e1fe8daaf4b42...
5904  0xbe27f6f4713ecda703dc5dbc4b9fa4b3031afebb3e53...
5905  0x857a4bf0d8f0a8433752bb3f6d9406a799e272d82732...
5906  0x05d3a9d3b294a1cb0d29925f21d8429ec36b4667a3f3...
5907  0x4a8a09844ee4e0ee5f0097b825f3dddc39d1654f350e...

                                                tokenId priceETH  \
0     1157920892373161954235709850086879078110749711...      7.2
1              9868188640707215440437863615521278132314        6
2             11569600475311907757754736652680119189493        0
3     1157920892373161954235709850086879078154986419...      6.5
4             11909882842232846221218111260111887400865        0
...                                                 ...      ...
5903  1157920892373161954235709850086879078362558663...    3.397
5904  1157920892373161954235709850086879078372767134...     3.75
5905  1157920892373161954235709850086879078372767134...     3.75
5906  1157920892373161954235709850086879078369364310...     3.75
5907  1157920892373161954235709850086879078090332769...      3.3

               timestamp         collection transaction_date
0    2022-02-25 00:49:55  Decentraland LAND       2022-02-25
1    2022-02-24 05:54:29  Decentraland LAND       2022-02-24
2    2022-02-22 20:07:50  Decentraland LAND       2022-02-22
3    2022-02-22 04:27:27  Decentraland LAND       2022-02-22
4    2022-02-21 19:09:38  Decentraland LAND       2022-02-21
...                  ...                ...              ...
5903 2022-06-15 16:38:39  Decentraland LAND       2022-06-15
5904 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
5905 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
5906 2022-06-15 13:15:44  Decentraland LAND       2022-06-15
5907 2022-06-14 19:33:20  Decentraland LAND       2022-06-14

[5908 rows x 6 columns]

In [35]:
#Extracting data with USD prices for daily prices conversion from WETH to USD

url2 = 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2'

# initialize full_data for Query2 of Prices dataset
df3_fulldata = pd.DataFrame()
df1_data = pd.DataFrame()

# Set query (which uses text input to specify USD data)
query = '''query {
  tokenDayDatas(where:{token:"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"}, orderBy: date, orderDirection: desc, first: 1000){
    token{
      symbol
    }
    priceUSD
    date
  }
}'''

# Make the request
r = requests.post(url2, json={'query': query})
#print(r.status_code)
#print(r.text)
    
# JSON adjustment 
json_data = json.loads(r.text)
    
# extract JSON to convert to a dataframe
df1_data = json_data['data']['tokenDayDatas']
df3_fulldata = pd.DataFrame(df1_data)

#Removing NULLS - Data Cleaning
df2 = df3_fulldata.dropna()

#Converting from Unix timestamp to datetime
df2['date'] = pd.to_datetime(df2['date'],unit='s')

#Removing extra data from columns : Cleaning
df2['token'] = df2['token'].map(lambda x: str(x)[12:-2])

In [40]:
#To match the datatypes before joining the dataframes - df = 
df1 = df.copy()

df2['transaction_date'] = df2['date']
df1['transaction_date']=df1['transaction_date'].astype('datetime64')
df2['Value_priceUSD'] = pd.to_numeric(df2['priceUSD'])
df1['priceETH'] = pd.to_numeric(df1['priceETH'])


print(df2)

    token                             priceUSD       date transaction_date  \
0    WETH  1349.905748803015789175893169609904 2022-09-23       2022-09-23
1    WETH  1328.014952605661695422075237383526 2022-09-22       2022-09-22
2    WETH  1250.373657230519795747548793091669 2022-09-21       2022-09-21
3    WETH  1322.338769529879602565735177039721 2022-09-20       2022-09-20
4    WETH  1378.714089021366009048366306045291 2022-09-19       2022-09-19
..    ...                                  ...        ...              ...
865  WETH  211.2700070720423180044098891861044 2020-05-11       2020-05-11
866  WETH  212.0966244894944114669950211274562 2020-05-08       2020-05-08
867  WETH  201.3586620865843805374897241587202 2020-05-07       2020-05-07
868  WETH  201.3584584250841171798806544377829 2020-05-06       2020-05-06
869  WETH  201.4862508610671222650693075518426 2020-05-05       2020-05-05

     Value_priceUSD
0       1349.905749
1       1328.014953
2       1250.373657
3       1322.338770
4       1378.714089
..              ...
865      211.270007
866      212.096624
867      201.358662
868      201.358458
869      201.486251

[870 rows x 5 columns]

In [41]:
#Left join on the above 2 dataframes based on 'Date'
df_final = pd.merge(df1, df2[['Value_priceUSD', 'transaction_date']], on='transaction_date', how='left')

#Calculating price in USD based on daily USD rate
df_final['TokenPrice_USD'] = df_final['Value_priceUSD'] * df_final['priceETH']
df_final.sort_values(by=['transaction_date'], inplace=True, ascending=False)

#Dropping the redundant columns
df_final = df_final.drop(['timestamp'], axis=1)
#df_final = df_final.drop(['Value_priceUSD'], axis=1)

print(df_final)

                                                     id  \
5600  0x4cec98fe6bb429b5f93f5f0b800001a2de0e276ca503...
5601  0x1c3d526ac2599057e759268d58307881667218a4649a...
5602  0xc4381bc367695c9629763311ba0580869166c7f4da7c...
5603  0x0e89f66a3c9787430e693084dafabc5802d42b70e748...
5604  0x47b2f2f3fcc2af5c3da9117547acb1036e7befe79f19...
...                                                 ...
4610  0xc505d53ff6353775a1d933676a11671be6cf8ec6a9bb...
4611  0xe4a89aeb397da530558e4db7a09598e117581367c83d...
4612  0xf1f90e1169c7b0945e11124e737dcd6958668cb254f9...
4614  0xbdec6eac54415407e151986b0273f8efd92e6c271263...
4613  0xa6b0765ac5d3d5074dcfde4f6224be79adbef576b106...

                                                tokenId  priceETH  \
5600          26882306986754138613606593987109688705054     2.300
5601  1157920892373161954235709850086879078029081943...     1.787
5602          11229318108390969294291362045248350978064     1.900
5603  1157920892373161954235709850086879078029081943...     1.780
5604          26542024619833200150143219379677920493464     1.788
...                                                 ...       ...
4610          15993271245284107782778606549293105938582     1.750
4611  1157920892373161954235709850086879078226445716...     1.000
4612  1157920892373161954235709850086879078226445716...     0.950
4614          18375247813730677027022228801315483418537     0.010
4613          18375247813730677027022228801315483418537     0.010

             collection transaction_date  Value_priceUSD  TokenPrice_USD
5600  Decentraland LAND       2022-09-22     1328.014953     3054.434391
5601  Decentraland LAND       2022-09-21     1250.373657     2234.417725
5602  Decentraland LAND       2022-09-21     1250.373657     2375.709949
5603  Decentraland LAND       2022-09-21     1250.373657     2225.665110
5604  Decentraland LAND       2022-09-21     1250.373657     2235.668099
...                 ...              ...             ...             ...
4610  Decentraland LAND       2018-07-21             NaN             NaN
4611  Decentraland LAND       2018-07-20             NaN             NaN
4612  Decentraland LAND       2018-07-20             NaN             NaN
4614  Decentraland LAND       2018-06-13             NaN             NaN
4613  Decentraland LAND       2018-06-13             NaN             NaN

[5908 rows x 7 columns]

In [43]:
df_final = df_final.drop(['Value_priceUSD'], axis=1)

In [ ]:
df_final.to_csv(r'C:\Users\Nehal\OneDrive\Documents\Nehal_Personal\Blockchain_Project\Data_Metaverse\LatestVideoOpenSeaDecentraland.csv', index = False)

In [48]:
###Getting the other dataset
datacsv = pd.read_csv("C:/Users/Nehal/OneDrive/Documents/Nehal_Personal/Blockchain_Project/TheGraph_Decentraland.csv")#To load it from local
dfNew = pd.DataFrame(datacsv)
print(dfNew)

      Unnamed: 0                                                 id  \
0           8999  0x860e4d334d8f593e2e0846365ac9e22aa915a004cb7a...
1           8998  0x288e87424022806b2eef24edeaaf252fa524703865b3...
2           8997  0xc0fed5fea1d243865a950a82a6b7cf209656b27f9574...
3           8996  0xfd0929aa28281e202e16139e5d3a6794f77c0e4f0955...
4           8995  0x366de20ada4a9849354a9c3c783ebd0595f78dad66d9...
...          ...                                                ...
8995           4  0x5a9610e6490fd96b7ff7e125a05e691c3ad288d19488...
8996           3  0x9463c0aceb0c5f0a4884eedef9a2c03763b051ba5584...
8997           2  0x828c72c2d662942d1bd16986663ef1c42e8f6342cfbe...
8998           1  0xe6fc6d58527e16b47a5587f39f786cc5ec879857d1f4...
8999           0  0xbc79ff3843d8678425df0e8b0a7b1a67688720b78a8b...

                                                 txHash  \
0     0xf2649959a88fb86a6222ae2dafd12d5f1bd38dfaaab0...
1     0xd399e26fa04a31e35dbf0f24802567b7cde52ea36f91...
2     0xfbae29a2bdad80323357c913a7915547a054953a3ed6...
3     0xa08fa9cb8232ea23e748894e63ee8a420e7ecadfa013...
4     0xecb36f7fea714dda9d2b57ea5df7bc00a0eebc032ffb...
...                                                 ...
8995  0x3e469f36d14e9e9badaf4fa3ee95a815b0b8335f0e59...
8996  0x75908d5fa94db1cf3a9d2077620a1010ad728bbdf0dc...
8997  0x755a715b8abb8cc06ffd1675c21295f1407b586b9bae...
8998  0x1feac3e83983edf6c9be54c3d0cf1f97a902ea041a3c...
8999  0x6f83d5560c81276a2d9117c11cbeb9aa3a2a710fa961...

                                           owner  \
0     0x4a34d03130503961f656fb9d26c5aec511d8eccc
1     0x4a34d03130503961f656fb9d26c5aec511d8eccc
2     0xf15d7066b78a4e969deefa1e4ca945212ddd3171
3     0x5ce213893956bbf4249a7f8a079331280065eec6
4     0xf179344bbec75ad4522bd6b2c780b2e13b3469a2
...                                          ...
8995  0x81e4fb0c64bf49f89b57f6648562fc9a791b2e92
8996  0x86b7055acbc68d5ad604ee0fbf14a86370601807
8997  0x3a1948c2993047abbf93b85ccce1f1ff983da65b
8998  0x99a811e5c62add613975456292f836115aea0164
8999  0xb860111670b78f47a0c1b3a4838b8259a2197f25

                                           buyer status  \
0     0x4c1f9ea2581f08551332ef52f0ff131a661e0946   sold
1     0x4c1f9ea2581f08551332ef52f0ff131a661e0946   sold
2     0x4b78c38753d9408c9039d3751757d0ec32b18dc4   sold
3     0xd84d7173eded010123443173715a338f681d7d53   sold
4     0x05dc04bba63eb9a570537d578b0619acdf3b744c   sold
...                                          ...    ...
8995  0x0ed1c03d04c1fbb33a0f25ef6147ab5a73d811a7   sold
8996  0xc1a1a63c331fc442bbbd04f32b923f8aa5f9f954   sold
8997  0x5abdc3cb826fc0277d642c9fb52fa76fe3abb4e7   sold
8998  0x17820aee2388abdbc81b4b407140016d50c086df   sold
8999  0x1b39eafd09f501c863e05b71d9cf01adc7c39138   sold

                                                tokenId category  \
0             20757224382177246271265851053337860898797   parcel
1             20757224382177246271265851053337860898799   parcel
2     1157920892373161954235709850086879078532699846...   parcel
3     1157920892373161954235709850086879078270682424...   parcel
4     1157920892373161954235709850086879078246862658...   parcel
...                                                 ...      ...
8995  1157920892373161954235709850086879078025679119...   parcel
8996          28924001188279769394386841631700297973621   parcel
8997  1157920892373161954235709850086879078086929945...   parcel
8998  1157920892373161954235709850086879078025679119...   parcel
8999  1157920892373161954235709850086879078294502189...   parcel

                createdAt    x    y  price_MANA        date  priceUSD  \
0     2022-01-25 23:49:01   60  -19      5349.0  2022-01-25   2.12694
1     2022-01-25 23:48:55   60  -17      5420.0  2022-01-25   2.12694
2     2022-01-25 23:02:40   -1 -122      8888.0  2022-01-25   2.12694
3     2022-01-25 21:41:12  -77   35      6249.0  2022-01-25   2.12694
4     2022-01-25 18:08:27  -85  -14      7488.0  2022-01-25   2.12694
...                   ...  ...  ...         ...         ...       ...
8995  2018-10-12 05:22:18 -150 -129     14899.0  2018-10-12       NaN
8996  2018-10-12 04:42:01   84 -139     20000.0  2018-10-12       NaN
8997  2018-10-12 02:20:57 -132  -71     17450.0  2018-10-12       NaN
8998  2018-10-12 01:56:40 -150   -4     47500.0  2018-10-12       NaN
8999  2018-10-11 19:57:58  -70  145     32000.0  2018-10-11       NaN

         price_USD
0     11377.001244
1     11528.013973
2     18904.241363
3     13291.247106
4     15926.525577
...            ...
8995           NaN
8996           NaN
8997           NaN
8998           NaN
8999           NaN

[9000 rows x 15 columns]

In [59]:
#Left join on the above 2 dataframes based on 'Date'
df_Opensea = pd.merge(df_final, dfNew[['x', 'y','tokenId','createdAt','price_MANA']], on ='tokenId', how='left')
df_Opensea.drop(df_Opensea.index[df_Opensea['TokenPrice_USD'] == 0], inplace = True)
df_Opensea = df_Opensea.dropna()


print(df_Opensea)

                                                     id  \
0     0x4cec98fe6bb429b5f93f5f0b800001a2de0e276ca503...
2     0xc4381bc367695c9629763311ba0580869166c7f4da7c...
3     0xc4381bc367695c9629763311ba0580869166c7f4da7c...
10    0x4c112e14c6a909ae504a714ce7e7052407cc28aa224d...
11    0x6b33bb8aaea2977b465732d2094fb52a09dcdd9869a0...
...                                                 ...
7650  0xd0be4dca69a1499b4b0f5c45d9d72d9ffd3152bc5410...
7651  0xd0be4dca69a1499b4b0f5c45d9d72d9ffd3152bc5410...
7652  0xee3f0c803b3eaa84f46f6c0bed7ff8d765d350cdfb19...
7653  0xee3f0c803b3eaa84f46f6c0bed7ff8d765d350cdfb19...
7654  0xee3f0c803b3eaa84f46f6c0bed7ff8d765d350cdfb19...

                                                tokenId  priceETH  \
0             26882306986754138613606593987109688705054      2.30
2             11229318108390969294291362045248350978064      1.90
3             11229318108390969294291362045248350978064      1.90
10    1157920892373161954235709850086879078420406665...      2.00
11    1157920892373161954235709850086879078029081943...      1.75
...                                                 ...       ...
7650          13271012309916600075071609689838960246731      3.40
7651          13271012309916600075071609689838960246731      3.40
7652          13271012309916600075071609689838960246731      2.75
7653          13271012309916600075071609689838960246731      2.75
7654          13271012309916600075071609689838960246731      2.75

             collection transaction_date  TokenPrice_USD      x      y  \
0     Decentraland LAND       2022-09-22     3054.434391   79.0   30.0
2     Decentraland LAND       2022-09-21     2375.709949   33.0   16.0
3     Decentraland LAND       2022-09-21     2375.709949   33.0   16.0
10    Decentraland LAND       2022-09-19     2757.428178  -33.0   73.0
11    Decentraland LAND       2022-09-18     2332.806675 -149.0 -135.0
...                 ...              ...             ...    ...    ...
7650  Decentraland LAND       2020-05-18      723.758577   38.0  -53.0
7651  Decentraland LAND       2020-05-18      723.758577   38.0  -53.0
7652  Decentraland LAND       2020-05-13      558.892914   38.0  -53.0
7653  Decentraland LAND       2020-05-13      558.892914   38.0  -53.0
7654  Decentraland LAND       2020-05-13      558.892914   38.0  -53.0

                createdAt  price_MANA
0     2020-02-01 07:18:18     18498.0
2     2021-11-17 11:01:00      4000.0
3     2021-11-16 00:09:27      2000.0
10    2018-12-19 09:55:10     13999.0
11    2020-11-24 22:12:48      7777.0
...                   ...         ...
7650  2019-10-02 21:55:49     32000.0
7651  2019-02-17 12:14:34     29000.0
7652  2020-07-08 11:53:18     26999.0
7653  2019-10-02 21:55:49     32000.0
7654  2019-02-17 12:14:34     29000.0

[3201 rows x 10 columns]

In [60]:
df_Opensea.to_csv(r'C:\Users\Nehal\OneDrive\Documents\Nehal_Personal\Blockchain_Project\Data_Metaverse\TestingNewData.csv', index = False)